### ISSUE TITLE
DllNotFoundException

### ISSUE THREAD

**Issue by MaiReo** [OpenSkywalking/skywalking-netcore#110]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
Platform: Windows 10 x64 17134.376 
dotnet --version
2.1.500
skywalking store: C:\Program Files\dotnet\store
skywalking deps: C:\Program Files\dotnet\x64\additionalDeps\skywalking.agent.aspnetcore

code is here: https://github.com/MaiReo/skysample

I was followed the "Getting Started" section at README. but i got

```
D:\Repos\dev\sky_sample>set ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyWalking.Agent.AspNetCore

D:\Repos\dev\sky_sample>set DOTNET_ADDITIONAL_DEPS="C:\Program Files\dotnet\x64\additionalDeps\skywalking.agent.aspnetcore"

D:\Repos\dev\sky_sample>dotnet run
从 D:\Repos\dev\sky_sample\Properties\launchSettings.json 使用启动设置...
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\MaiReo\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Development
Content root path: D:\Repos\dev\sky_sample
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[11]
      Hosting startup assembly exception
System.InvalidOperationException: Startup assembly SkyWalking.Agent.AspNetCore failed to execute. See the inner exception for more details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'SkyWalking.Agent.AspNetCore, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   --- End of inner exception stack trace ---

```

**Comment by liuhaoyang** [comment]
Make sure `dotnet run` in Administrator mode

**Comment by MaiReo** [comment]
Tried with no luck.
![image](https://user-images.githubusercontent.com/11777709/49354131-3e2b0b80-f6fc-11e8-8357-be012e1b2991.png)

**Comment by MaiReo** [comment]
I'll try on linux later.

**Comment by MaiReo** [comment]
```
maireo@RD-BuildAgent:~/dev/Middleware.Skywalking/demo$ sudo dotnet skywalking install
No executable found matching command "dotnet-skywalking"
maireo@RD-BuildAgent:~/dev/Middleware.Skywalking/demo$ locate dotnet-skywalking
maireo@RD-BuildAgent:~/dev/Middleware.Skywalking/demo$ which dotnet-skywalking
/home/maireo/.dotnet/tools/dotnet-skywalking
maireo@RD-BuildAgent:~/dev/Middleware.Skywalking/demo$ dotnet skywalking install
*********************************************************************
*                                                                   *
*                   Welcome to Apache SkyWalking                    *
*                                                                   *
*********************************************************************
Installing SkyWalking .NET Core Agent ...

Create tmp directory '/tmp/skywalking.agent.aspnetcore'
正克隆到 '/tmp/skywalking.agent.aspnetcore/repo'...
Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
/usr/share/dotnet/sdk/2.1.403/NuGet.targets(498,5): error : Unable to obtain lock file access on '/tmp/NuGetScratch/lock/14bff39f5fdb6b759eca94d978f1b84c226e6f29' for operations on '/home/maireo/.nuget/NuGet/NuGet.Config'. This may mean that a different user or administator is holding this lock and that this process does not have permission to access it. If no other process is currently performing an operation on this file it may mean that an earlier NuGet process crashed and left an inaccessible lock file, in this case removing the file '/tmp/NuGetScratch/lock/14bff39f5fdb6b759eca94d978f1b84c226e6f29' will allow NuGet to continue. [/tmp/skywalking.agent.aspnetcore/repo/manifest/SkyWalking.Runtime.Store.csproj]
Build FAILED.
/usr/share/dotnet/sdk/2.1.403/NuGet.targets(498,5): error : Unable to obtain lock file access on '/tmp/NuGetScratch/lock/14bff39f5fdb6b759eca94d978f1b84c226e6f29' for operations on '/home/maireo/.nuget/NuGet/NuGet.Config'. This may mean that a different user or administator is holding this lock and that this process does not have permission to access it. If no other process is currently performing an operation on this file it may mean that an earlier NuGet process crashed and left an inaccessible lock file, in this case removing the file '/tmp/NuGetScratch/lock/14bff39f5fdb6b759eca94d978f1b84c226e6f29' will allow NuGet to continue. [/tmp/skywalking.agent.aspnetcore/repo/manifest/SkyWalking.Runtime.Store.csproj]
    0 Warning(s)
    1 Error(s)
Time Elapsed 00:00:31.60
Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
/usr/share/dotnet/sdk/2.1.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ComposeStore.targets(269,5): error MSB3191: Unable to create directory "/usr/local/share/dotnet/store/x64/netcoreapp2.1/". Access to the path '/usr/local/share/dotnet/store/x64/netcoreapp2.1/' is denied. [/tmp/skywalking.agent.aspnetcore/repo/manifest/SkyWalking.Runtime.Store.csproj]
maireo@RD-BuildAgent:~/dev/Middleware.Skywalking/demo$ sudo dotnet skywalking install
No executable found matching command "dotnet-skywalking"
maireo@RD-BuildAgent:~/dev/Middleware.Skywalking/demo$ uname -a
Linux RD-BuildAgent 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
maireo@RD-BuildAgent:~/dev/Middleware.Skywalking/demo$ cat /etc/issue
Ubuntu 16.04.5 LTS \n \l

maireo@RD-BuildAgent:~/dev/Middleware.Skywalking/demo$ dotnet info
No executable found matching command "dotnet-info"
maireo@RD-BuildAgent:~/dev/Middleware.Skywalking/demo$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
Should I use root user instead?

**Comment by MaiReo** [comment]
```
root@RD-BuildAgent:/home/maireo/dev/Middleware.Skywalking/demo/netcoreapp2.1# ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyWalking.Agent.AspNetCore \ DOTNET_ADDITIONAL_DEPS=/usr/local/share/dotnet/x64/additionalDeps/skywalking.agent.aspnetcore SKYWALKING__APPLICATIONCODE=dotnet_sample dotnet run^C
root@RD-BuildAgent:/home/maireo/dev/Middleware.Skywalking/demo/netcoreapp2.1# ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyWalking.Agent.AspNetCore \
>  DOTNET_ADDITIONAL_DEPS=/usr/local/share/dotnet/x64/additionalDeps/skywalking.agent.aspnetcore \
> SKYWALKING__APPLICATIONCODE=dotnet_sample \
> dotnet run
Using launch settings from /home/maireo/dev/Middleware.Skywalking/demo/netcoreapp2.1/Properties/launchSettings.json...
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Hosting environment: Development
Content root path: /home/maireo/dev/Middleware.Skywalking/demo/netcoreapp2.1
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[11]
      Hosting startup assembly exception
System.InvalidOperationException: Startup assembly SkyWalking.Agent.AspNetCore failed to execute. See the inner exception for more details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'SkyWalking.Agent.AspNetCore, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   --- End of inner exception stack trace ---
Now listening on: http://localhost:15888
Application started. Press Ctrl+C to shut down.
^CApplication is shutting down...
root@RD-BuildAgent:/home/maireo/dev/Middleware.Skywalking/demo/netcoreapp2.1# ls /usr/local/share/dotnet/x64/additionalDeps/skywalking.agent.aspnetcore
ls: 无法访问'/usr/local/share/dotnet/x64/additionalDeps/skywalking.agent.aspnetcore': 没有那个文件或目录
root@RD-BuildAgent:/home/maireo/dev/Middleware.Skywalking/demo/netcoreapp2.1# ls /usr/local/share/do
doc/    dotnet/
root@RD-BuildAgent:/home/maireo/dev/Middleware.Skywalking/demo/netcoreapp2.1# ls /usr/local/share/dotnet/store/x64/netcoreapp2.1/
artifact.xml                                             microsoft.extensions.configuration.abstractions/         microsoft.net.http.headers/                              skywalking.diagnostics.entityframeworkcore/
google.protobuf/                                         microsoft.extensions.configuration.binder/               mysqlconnector/                                          skywalking.diagnostics.entityframeworkcore.npgsql/
grpc.core/                                               microsoft.extensions.configuration.environmentvariables/ newtonsoft.json/                                         skywalking.diagnostics.entityframeworkcore.pomelo.mysql/
microsoft.aspnetcore.hosting.abstractions/               microsoft.extensions.configuration.fileextensions/       npgsql/                                                  skywalking.diagnostics.httpclient/
microsoft.aspnetcore.hosting.server.abstractions/        microsoft.extensions.configuration.json/                 npgsql.entityframeworkcore.postgresql/                   skywalking.diagnostics.sqlclient/
microsoft.aspnetcore.http.abstractions/                  microsoft.extensions.dependencyinjection/                pomelo.entityframeworkcore.mysql/                        skywalking.transport.grpc/
microsoft.aspnetcore.http.extensions/                    microsoft.extensions.dependencyinjection.abstractions/   pomelo.jsonobject/                                       skywalking.utilities.configuration/
microsoft.aspnetcore.http.features/                      microsoft.extensions.fileproviders.abstractions/         remotion.linq/                                           skywalking.utilities.dependencyinjection/
microsoft.aspnetcore.mvc.abstractions/                   microsoft.extensions.fileproviders.physical/             serilog/                                                 skywalking.utilities.logging/
microsoft.aspnetcore.routing.abstractions/               microsoft.extensions.filesystemglobbing/                 serilog.extensions.logging/                              system.data.sqlclient/
microsoft.entityframeworkcore/                           microsoft.extensions.hosting.abstractions/               serilog.sinks.file/                                      system.interactive.async/
microsoft.entityframeworkcore.design/                    microsoft.extensions.logging/                            serilog.sinks.rollingfile/                               system.runtime.compilerservices.unsafe/
microsoft.entityframeworkcore.relational/                microsoft.extensions.logging.abstractions/               skywalking.abstractions/                                 system.text.encoding.codepages/
microsoft.extensions.caching.abstractions/               microsoft.extensions.logging.console/                    skywalking.agent.aspnetcore/                             system.text.encodings.web/
microsoft.extensions.caching.memory/                     microsoft.extensions.options/                            skywalking.core/
microsoft.extensions.configuration/                      microsoft.extensions.primitives/                         skywalking.diagnostics.aspnetcore/
root@RD-BuildAgent:/home/maireo/dev/Middleware.Skywalking/demo/netcoreapp2.1# ls /usr/local/share/dotnet/store/x64/netcoreapp2.1/skywalking.
skywalking.abstractions/                                 skywalking.diagnostics.entityframeworkcore/              skywalking.diagnostics.sqlclient/                        skywalking.utilities.logging/
skywalking.agent.aspnetcore/                             skywalking.diagnostics.entityframeworkcore.npgsql/       skywalking.transport.grpc/
skywalking.core/                                         skywalking.diagnostics.entityframeworkcore.pomelo.mysql/ skywalking.utilities.configuration/
skywalking.diagnostics.aspnetcore/                       skywalking.diagnostics.httpclient/                       skywalking.utilities.dependencyinjection/
root@RD-BuildAgent:/home/maireo/dev/Middleware.Skywalking/demo/netcoreapp2.1# ls /usr/local/share/dotnet/store/x64/netcoreapp2.1/skywalking.a
skywalking.abstractions/     skywalking.agent.aspnetcore/
root@RD-BuildAgent:/home/maireo/dev/Middleware.Skywalking/demo/netcoreapp2.1# ls /usr/local/share/dotnet/store/x64/netcoreapp2.1/skywalking.agent.aspnetcore/0.6.0-prerelease-55783105/lib/netstandard2.0/
SkyWalking.Agent.AspNetCore.dll
root@RD-BuildAgent:/home/maireo/dev/Middleware.Skywalking/demo/netcoreapp2.1# ls /usr/local/share/dotnet/store/x64/netcoreapp2.1/skywalking.agent.aspnetcore/0.6.0-prerelease-55783105/lib/netstandard2.0/^C
root@RD-BuildAgent:/home/maireo/dev/Middleware.Skywalking/demo/netcoreapp2.1# ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyWalking.Agent.AspNetCore  DOTNET_ADDITIONAL_DEPS=/usr/local/share/dotnet/x64/skywalking.agent.aspnetcore SKYWALKING__APP
LICATIONCODE=dotnet_sample dotnet run
Using launch settings from /home/maireo/dev/Middleware.Skywalking/demo/netcoreapp2.1/Properties/launchSettings.json...
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Hosting environment: Development
Content root path: /home/maireo/dev/Middleware.Skywalking/demo/netcoreapp2.1
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[11]
      Hosting startup assembly exception
System.InvalidOperationException: Startup assembly SkyWalking.Agent.AspNetCore failed to execute. See the inner exception for more details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'SkyWalking.Agent.AspNetCore, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   --- End of inner exception stack trace ---
Now listening on: http://localhost:15888
Application started. Press Ctrl+C to shut down.
^CApplication is shutting down...
```
No luck (;_;)

**Comment by liuhaoyang** [comment]
Now it seems that the `dotnet cli` does raise the threshold for the use of SkyWalking .NET Core Agent, and we will consider another, simpler way to use the SkyWalking .NET Core.

**Comment by liuhaoyang** [comment]
You can use SkyWalking .NET Core Agent. manually as follows
```
dotnet add package SkyWalking.Agent.AspNetCore
set ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyWalking.Agent.AspNetCore (on windows)
dotnet run your_application
```

**Comment by MaiReo** [comment]
Thank you man,  I'll try later.

**Comment by MaiReo** [comment]
Cannot use in VS debugging mode.
And in console. the agent is not read the json file. it tried to connect localhost, may the hard-coded default settings.
uses dotnet core 2.2 + asp net core 2.2.
```
maireo@MAIREO-LAPTOP:/mnt/d/Repos/housecool/Core.DualCall/src/Core.DualCall.Web/logs$ tail -f SkyWalking-20181225.log
2018-12-25 09:59:39.470 +08:00 [My_Application] [Information] SkyWalking.Transport.Grpc.GrpcStateCheckService : Loaded instrument service [SkyWalking.Transport.Grpc.GrpcStateCheckService].
2018-12-25 09:59:39.476 +08:00 [My_Application] [Information] SkyWalking.Diagnostics.TracingDiagnosticProcessorObserver : Loaded diagnostic listener [Microsoft.EntityFrameworkCore].
2018-12-25 09:59:39.477 +08:00 [My_Application] [Information] SkyWalking.Diagnostics.TracingDiagnosticProcessorObserver : Loaded diagnostic listener [Microsoft.AspNetCore].
2018-12-25 09:59:39.477 +08:00 [My_Application] [Information] SkyWalking.SkyWalkingAgentStartup : Started SkyWalking .NET Core Agent.
2018-12-25 09:59:49.570 +08:00 [My_Application] [Error] SkyWalking.Transport.Grpc.ConnectionManager : Connect collector timeout.
System.Threading.Tasks.TaskCanceledException: Reached deadline.
   at Grpc.Core.Channel.WaitForStateChangedAsync(ChannelState lastObservedState, Nullable`1 deadline) in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:line 139
   at Grpc.Core.Channel.ConnectAsync(Nullable`1 deadline) in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:line 220   at SkyWalking.Transport.Grpc.ConnectionManager.ConnectAsync()
2018-12-25 09:59:54.500 +08:00 [My_Application] [Information] SkyWalking.Transport.Grpc.ConnectionManager : Shutdown connection[localhost:11800].
2018-12-25 10:00:04.503 +08:00 [My_Application] [Error] SkyWalking.Transport.Grpc.ConnectionManager : Connect collector timeout.
System.Threading.Tasks.TaskCanceledException: Reached deadline.
   at Grpc.Core.Channel.WaitForStateChangedAsync(ChannelState lastObservedState, Nullable`1 deadline) in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:line 139
   at Grpc.Core.Channel.ConnectAsync(Nullable`1 deadline) in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:line 220
   at SkyWalking.Transport.Grpc.ConnectionManager.ConnectAsync()
2018-12-25 10:00:09.481 +08:00 [My_Application] [Information] SkyWalking.Transport.Grpc.ConnectionManager : Shutdown connection[localhost:11800].
2018-12-25 10:00:19.484 +08:00 [My_Application] [Error] SkyWalking.Transport.Grpc.ConnectionManager : Connect collector timeout.
System.Threading.Tasks.TaskCanceledException: Reached deadline.
   at Grpc.Core.Channel.WaitForStateChangedAsync(ChannelState lastObservedState, Nullable`1 deadline) in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:line 139
   at Grpc.Core.Channel.ConnectAsync(Nullable`1 deadline) in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:line 220
   at SkyWalking.Transport.Grpc.ConnectionManager.ConnectAsync()
2018-12-25 10:00:24.477 +08:00 [My_Application] [Information] SkyWalking.Transport.Grpc.ConnectionManager : Shutdown connection[localhost:11800].
^C
maireo@MAIREO-LAPTOP:/mnt/d/Repos/housecool/Core.DualCall/src/Core.DualCall.Web/logs$ ls
SkyWalking-20181225.log
maireo@MAIREO-LAPTOP:/mnt/d/Repos/housecool/Core.DualCall/src/Core.DualCall.Web/logs$ tail -f SkyWalking-20181225.log
*                                                             *
***************************************************************

2018-12-25 10:02:04.558 +08:00 [My_Application] [Information] SkyWalking.Service.TraceSegmentTransportService : Loaded instrument service [SkyWalking.Service.TraceSegmentTransportService].
2018-12-25 10:02:04.559 +08:00 [My_Application] [Information] SkyWalking.Service.ServiceDiscoveryService : Loaded instrument service [SkyWalking.Service.ServiceDiscoveryService].
2018-12-25 10:02:04.559 +08:00 [My_Application] [Information] SkyWalking.Service.SamplingRefreshService : Loaded instrument service [SkyWalking.Service.SamplingRefreshService].
2018-12-25 10:02:04.559 +08:00 [My_Application] [Information] SkyWalking.Transport.Grpc.GrpcStateCheckService : Loaded instrument service [SkyWalking.Transport.Grpc.GrpcStateCheckService].
2018-12-25 10:02:04.564 +08:00 [My_Application] [Information] SkyWalking.Diagnostics.TracingDiagnosticProcessorObserver : Loaded diagnostic listener [Microsoft.EntityFrameworkCore].
2018-12-25 10:02:04.565 +08:00 [My_Application] [Information] SkyWalking.Diagnostics.TracingDiagnosticProcessorObserver : Loaded diagnostic listener [Microsoft.AspNetCore].
2018-12-25 10:02:04.565 +08:00 [My_Application] [Information] SkyWalking.SkyWalkingAgentStartup : Started SkyWalking .NET Core Agent.
2018-12-25 10:02:14.638 +08:00 [My_Application] [Error] SkyWalking.Transport.Grpc.ConnectionManager : Connect collector timeout.
System.Threading.Tasks.TaskCanceledException: Reached deadline.
   at Grpc.Core.Channel.WaitForStateChangedAsync(ChannelState lastObservedState, Nullable`1 deadline) in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:line 139
   at Grpc.Core.Channel.ConnectAsync(Nullable`1 deadline) in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:line 220
   at SkyWalking.Transport.Grpc.ConnectionManager.ConnectAsync()
2018-12-25 10:02:19.582 +08:00 [My_Application] [Information] SkyWalking.Transport.Grpc.ConnectionManager : Shutdown connection[localhost:11800].
^C
maireo@MAIREO-LAPTOP:/mnt/d/Repos/housecool/Core.DualCall/src/Core.DualCall.Web/logs$ cd ..
maireo@MAIREO-LAPTOP:/mnt/d/Repos/housecool/Core.DualCall/src/Core.DualCall.Web$ cat skywalking.json
{
  "SkyWalking": {
    "ApplicationCode": "core_dual_call",
    "SpanLimitPerSegment": 300,
    "Sampling": {
      "SamplePer3Secs": -1
    },
    "Logging": {
      "Level": "Information",
      "FilePath": "logs\\SkyWalking-{Date}.log"
    },
    "Transport": {
      "Interval": 3000,
      "PendingSegmentLimit": 30000,
      "PendingSegmentTimeout": 1000,
      "gRPC": {
        "Servers": "192.168.0.248:11800",
        "Timeout": 2000,
        "ConnectTimeout": 10000
      }
    }
  }
}
```
set program to read skywalking.json, no effect.
```
maireo@MAIREO-LAPTOP:/mnt/d/Repos/housecool/Core.DualCall/src/Core.DualCall.Web$ cat Program.cs
﻿using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Autofac.Extensions.DependencyInjection;
using Core.DualCall.Configuration;

namespace Core.DualCall
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureServices(services => services.AddAutofac())
                .ConfigureAppConfiguration(config => config.AddJsonFile("skywalking.json", true, false))
                .UseStartup<Startup>();
    }
}
```

**Comment by MaiReo** [comment]
set SKYWALKING__CONFIG__PATH works, yeah.

**Comment by MaiReo** [comment]
works both with dotnet run and dotnet <app>.dll on Windows 10 1803.
but not on ubuntu 18.04.  no log file of skywalking agent.
