### ISSUE TITLE
Connection processing ended abnormally System.InvalidOperationException: No active span.

### ISSUE THREAD

**Issue by zhouxin93** [OpenSkywalking/skywalking-netcore#66]
NetCore 2.1.1 + 阿里云 CentOS 容器 + SqlServer

经过测试发现(高并发下)：
1、直接Http访问无问题。
2、直接Http访问+业务处理无问题
3、Http访问+业务处理+Sqlserver操作。出现如下错误：

`Microsoft.AspNetCore.Server.Kestrel[0]
Connection processing ended abnormally.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: No active span.
at SkyWalking.Context.TracingContext.InternalActiveSpan()
at SkyWalking.AspNetCore.Diagnostics.HostingDiagnosticProcessor.EndRequest(HttpContext httpContext)
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at SkyWalking.Diagnostics.TracingDiagnosticMethod.Invoke(String diagnosticName, Object value)
at SkyWalking.Diagnostics.TracingDiagnosticObserver.OnNext(KeyValuePair`2 value)
at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
at Microsoft.AspNetCore.Hosting.Internal.HostingApplicationDiagnostics.RecordEndRequestDiagnostics(HttpContext httpContext, Int64 currentTimestamp)
at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.DisposeContext(Context context, Exception exception)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)`

**Comment by zhouxin93** [comment]
另一种错误：
`Connection processing ended abnormally.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.AspNetCore.Http.Extensions.UriHelper.GetDisplayUrl(HttpRequest request)
at SkyWalking.AspNetCore.Diagnostics.HostingDiagnosticProcessor.BeginRequest(HttpContext httpContext)
at SkyWalking.Diagnostics.TracingDiagnosticObserver.OnNext(KeyValuePair`2 value)
--- End of inner exception stack trace ---
at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
at Microsoft.AspNetCore.Hosting.Internal.HostingApplicationDiagnostics.RecordEndRequestDiagnostics(HttpContext httpContext, Int64 currentTimestamp)
at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.DisposeContext(Context context, Exception exception)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)`

**Comment by zhouxin93** [comment]
![tim 20180703144913](https://user-images.githubusercontent.com/20853017/42203112-5ec2053c-7ed0-11e8-9505-ce70c9043a77.png)

**Comment by wu-sheng** [comment]
It is great that someone is trying to deploy our .NET agent in Cloud under high throughput.
